### ISSUE TITLE
Rules Files added but Jobs are missing

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [mkuratczyk/prometheus-on-PCF#2]
Hi,

Just a small remark. I think you are missing some jobs in the Alertmanager because you are using the following alert rules:

```
rule_files:
          - /var/vcap/jobs/bosh_alerts/bosh_jobs.alerts
          - /var/vcap/jobs/bosh_alerts/bosh_processes.alerts
          - /var/vcap/jobs/bosh_alerts/bosh_system.alerts
          - /var/vcap/jobs/bosh_alerts/prometheus_bosh_exporter.alerts
          - /var/vcap/jobs/cloudfoundry_alerts/cf_routes.alerts
          - /var/vcap/jobs/cloudfoundry_alerts/diego.alerts
          - /var/vcap/jobs/cloudfoundry_alerts/prometheus_cf_exporter.alerts
          - /var/vcap/jobs/cloudfoundry_alerts/prometheus_firehose_exporter.alerts
          - /var/vcap/jobs/p_rabbitmq_alerts/p_rabbitmq.alerts
          - /var/vcap/jobs/p_redis_alerts/p_redis.alerts
          - /var/vcap/jobs/p_redis_alerts/p_redis_service_broker.alerts
          - /var/vcap/jobs/probe_alerts/probe.alerts
          - /var/vcap/jobs/prometheus_alerts/prometheus.alerts
          - /var/vcap/jobs/rabbitmq_alerts/rabbitmq.alerts
          - /var/vcap/jobs/redis_alerts/prometheus_redis_exporter.alerts
          - /var/vcap/jobs/redis_alerts/redis.alerts
```

There are rules of the jobs 'rabbitmq_alerts' and 'redis_alerts' but these jobs are missing in the deployment manifest I think.

```
  jobs:
  - name: bosh_alerts
    release: prometheus
  - name: cloudfoundry_alerts
    release: prometheus
  - name: mysql_alerts
    release: prometheus
  - name: p_rabbitmq_alerts
    release: prometheus
  - name: p_redis_alerts
    release: prometheus
  - name: probe_alerts
    release: prometheus
  - name: prometheus_alerts
    release: prometheus

```
